[package]
name = "rush"
version = "0.2.6"
authors = ["Hugo Wang <w@mitnk.com>"]

[dependencies]
# rustyline = "1.0.0"
rustyline = { git = "https://github.com/kkawakam/rustyline.git" }
ansi_term = "0.9"
shlex = "0.1.0"
libc = "0.2.0"
errno = "*"
nom = "^2.1"
regex = "0.2"
nix = "0.8.0"
sqlite = "0.23.0"
time = "0.1.0"
