[package]
build = "src/build.rs"
name = "cicada"
version = "0.9.2"
authors = ["Hugo Wang <w@mitnk.com>"]

description = "A simple Unix shell."
repository = "https://github.com/mitnk/cicada"
keywords = ["shell", "unix"]
categories = ["command-line-utilities", "command-line-interface", "development-tools"]
license = "MIT"

[lib]
name = "cicada"
path = "src/lib.rs"

[[bin]]
name = "cicada"
doc = false

[dependencies]
errno = "0.2.0"
exec = "0.3.0"
glob = "0.2.0"
libc = "0.2.0"
linefeed = "0.5.0"
nix = "0.11.0"
nom = "3.0"
regex = "1.0.0"
time = "0.1"
yaml-rust = "0.4.0"

[dependencies.rusqlite]
version = "0.16.0"
features = ["bundled"]

[build-dependencies]
time = "0.1"
