[package]
name = "cicada"
version = "0.6.0"
authors = ["Hugo Wang <w@mitnk.com>"]

description = "A simple Unix shell."
repository = "https://github.com/mitnk/cicada"
keywords = ["shell", "unix"]
categories = ["command-line-utilities", "command-line-interface", "development-tools"]
license = "MIT"

[dependencies]
linefeed = "0.2.0"
libc = "0.2.0"
errno = "0.2.0"
nom = "^3.0"
regex = "0.2.0"
nix = "0.8.0"
sqlite = "0.23.0"
time = "0.1"
yaml-rust = "0.3.0"
glob = "0.2.0"
exec = "0.2.0"
