[package]
name = "cicada"
version = "0.3.1"
authors = ["Hugo Wang <w@mitnk.com>"]

[dependencies]
linefeed = "0.2"
ansi_term = "0.9"
shlex = "0.1.0"
libc = "0.2.0"
errno = "*"
nom = "^2.1"
regex = "0.2"
nix = "0.8.0"
sqlite = "0.23.0"
time = "0.1.0"
yaml-rust = "*"
